// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "ecs.proto" (package "u2.shared.proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Vector2 message
 *
 * @generated from protobuf message u2.shared.proto.Vector2Proto
 */
export interface Vector2Proto {
    /**
     * @generated from protobuf field: float x = 1
     */
    x: number;
    /**
     * @generated from protobuf field: float y = 2
     */
    y: number;
}
/**
 * Transform2D component
 *
 * @generated from protobuf message u2.shared.proto.Transform2DProto
 */
export interface Transform2DProto {
    /**
     * @generated from protobuf field: u2.shared.proto.Vector2Proto position = 1
     */
    position?: Vector2Proto;
    /**
     * @generated from protobuf field: float rotation = 2
     */
    rotation: number;
}
/**
 * Velocity component
 *
 * @generated from protobuf message u2.shared.proto.VelocityProto
 */
export interface VelocityProto {
    /**
     * @generated from protobuf field: u2.shared.proto.Vector2Proto linear = 1
     */
    linear?: Vector2Proto;
    /**
     * @generated from protobuf field: float angular = 2
     */
    angular: number;
}
/**
 * Mass component
 *
 * @generated from protobuf message u2.shared.proto.MassProto
 */
export interface MassProto {
    /**
     * @generated from protobuf field: float mass_kg = 1
     */
    massKg: number;
    /**
     * @generated from protobuf field: float inertia_kgm2 = 2
     */
    inertiaKgm2: number;
}
/**
 * Control state component
 *
 * @generated from protobuf message u2.shared.proto.ControlStateProto
 */
export interface ControlStateProto {
    /**
     * @generated from protobuf field: float thrust = 1
     */
    thrust: number;
    /**
     * @generated from protobuf field: float strafe_x = 2
     */
    strafeX: number;
    /**
     * @generated from protobuf field: float strafe_y = 3
     */
    strafeY: number;
    /**
     * @generated from protobuf field: float yaw_input = 4
     */
    yawInput: number;
}
/**
 * Flight assist component
 *
 * @generated from protobuf message u2.shared.proto.FlightAssistProto
 */
export interface FlightAssistProto {
    /**
     * @generated from protobuf field: bool enabled = 1
     */
    enabled: boolean;
}
/**
 * Health component
 *
 * @generated from protobuf message u2.shared.proto.HealthProto
 */
export interface HealthProto {
    /**
     * @generated from protobuf field: float current_hp = 1
     */
    currentHp: number;
    /**
     * @generated from protobuf field: float max_hp = 2
     */
    maxHp: number;
}
/**
 * Entity snapshot (for network sync)
 *
 * @generated from protobuf message u2.shared.proto.EntitySnapshotProto
 */
export interface EntitySnapshotProto {
    /**
     * @generated from protobuf field: uint32 entity_id = 1
     */
    entityId: number;
    /**
     * @generated from protobuf field: u2.shared.proto.Transform2DProto transform = 2
     */
    transform?: Transform2DProto;
    /**
     * @generated from protobuf field: u2.shared.proto.VelocityProto velocity = 3
     */
    velocity?: VelocityProto;
    /**
     * @generated from protobuf field: u2.shared.proto.ControlStateProto control_state = 4
     */
    controlState?: ControlStateProto;
    /**
     * @generated from protobuf field: u2.shared.proto.FlightAssistProto flight_assist = 5
     */
    flightAssist?: FlightAssistProto;
    /**
     * @generated from protobuf field: u2.shared.proto.HealthProto health = 6
     */
    health?: HealthProto;
    /**
     * @generated from protobuf field: uint32 last_processed_sequence = 7
     */
    lastProcessedSequence: number; // Last input sequence processed by server (M2.3 reconciliation)
}
/**
 * World snapshot (for network sync)
 *
 * @generated from protobuf message u2.shared.proto.WorldSnapshotProto
 */
export interface WorldSnapshotProto {
    /**
     * @generated from protobuf field: uint32 tick = 1
     */
    tick: number;
    /**
     * @generated from protobuf field: uint64 timestamp_ms = 2
     */
    timestampMs: bigint;
    /**
     * @generated from protobuf field: repeated u2.shared.proto.EntitySnapshotProto entities = 3
     */
    entities: EntitySnapshotProto[];
}
// ============================================================================
// M2.1: Network Protocol Messages
// ============================================================================

/**
 * Client -> Server: Player input commands
 *
 * @generated from protobuf message u2.shared.proto.PlayerInputProto
 */
export interface PlayerInputProto {
    /**
     * @generated from protobuf field: uint32 client_id = 1
     */
    clientId: number;
    /**
     * @generated from protobuf field: uint32 sequence_number = 2
     */
    sequenceNumber: number; // For input acknowledgment
    /**
     * @generated from protobuf field: uint64 timestamp_ms = 3
     */
    timestampMs: bigint; // Client timestamp
    /**
     * @generated from protobuf field: u2.shared.proto.ControlStateProto control_state = 4
     */
    controlState?: ControlStateProto;
    /**
     * @generated from protobuf field: bool flight_assist = 5
     */
    flightAssist: boolean; // FA:ON (true) or FA:OFF (false)
}
/**
 * Server -> Client: Connection accepted
 *
 * @generated from protobuf message u2.shared.proto.ConnectionAcceptedProto
 */
export interface ConnectionAcceptedProto {
    /**
     * @generated from protobuf field: uint32 client_id = 1
     */
    clientId: number; // Assigned client ID
    /**
     * @generated from protobuf field: uint32 entity_id = 2
     */
    entityId: number; // Assigned player entity ID
    /**
     * @generated from protobuf field: uint64 server_time_ms = 3
     */
    serverTimeMs: bigint; // Server time for synchronization
}
/**
 * Client -> Server: Connection request
 *
 * @generated from protobuf message u2.shared.proto.ConnectionRequestProto
 */
export interface ConnectionRequestProto {
    /**
     * @generated from protobuf field: string player_name = 1
     */
    playerName: string;
    /**
     * @generated from protobuf field: string version = 2
     */
    version: string; // Client version for compatibility check
}
/**
 * Server -> Client: Disconnect notification
 *
 * @generated from protobuf message u2.shared.proto.DisconnectProto
 */
export interface DisconnectProto {
    /**
     * @generated from protobuf field: uint32 client_id = 1
     */
    clientId: number;
    /**
     * @generated from protobuf field: string reason = 2
     */
    reason: string;
}
/**
 * Wrapper for all client-to-server messages
 *
 * @generated from protobuf message u2.shared.proto.ClientMessageProto
 */
export interface ClientMessageProto {
    /**
     * @generated from protobuf oneof: message
     */
    message: {
        oneofKind: "connectionRequest";
        /**
         * @generated from protobuf field: u2.shared.proto.ConnectionRequestProto connection_request = 1
         */
        connectionRequest: ConnectionRequestProto;
    } | {
        oneofKind: "playerInput";
        /**
         * @generated from protobuf field: u2.shared.proto.PlayerInputProto player_input = 2
         */
        playerInput: PlayerInputProto;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Wrapper for all server-to-client messages
 *
 * @generated from protobuf message u2.shared.proto.ServerMessageProto
 */
export interface ServerMessageProto {
    /**
     * @generated from protobuf oneof: message
     */
    message: {
        oneofKind: "connectionAccepted";
        /**
         * @generated from protobuf field: u2.shared.proto.ConnectionAcceptedProto connection_accepted = 1
         */
        connectionAccepted: ConnectionAcceptedProto;
    } | {
        oneofKind: "worldSnapshot";
        /**
         * @generated from protobuf field: u2.shared.proto.WorldSnapshotProto world_snapshot = 2
         */
        worldSnapshot: WorldSnapshotProto;
    } | {
        oneofKind: "disconnect";
        /**
         * @generated from protobuf field: u2.shared.proto.DisconnectProto disconnect = 3
         */
        disconnect: DisconnectProto;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class Vector2Proto$Type extends MessageType<Vector2Proto> {
    constructor() {
        super("u2.shared.proto.Vector2Proto", [
            { no: 1, name: "x", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "y", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<Vector2Proto>): Vector2Proto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.x = 0;
        message.y = 0;
        if (value !== undefined)
            reflectionMergePartial<Vector2Proto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Vector2Proto): Vector2Proto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float x */ 1:
                    message.x = reader.float();
                    break;
                case /* float y */ 2:
                    message.y = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Vector2Proto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float x = 1; */
        if (message.x !== 0)
            writer.tag(1, WireType.Bit32).float(message.x);
        /* float y = 2; */
        if (message.y !== 0)
            writer.tag(2, WireType.Bit32).float(message.y);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.Vector2Proto
 */
export const Vector2Proto = new Vector2Proto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Transform2DProto$Type extends MessageType<Transform2DProto> {
    constructor() {
        super("u2.shared.proto.Transform2DProto", [
            { no: 1, name: "position", kind: "message", T: () => Vector2Proto },
            { no: 2, name: "rotation", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<Transform2DProto>): Transform2DProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rotation = 0;
        if (value !== undefined)
            reflectionMergePartial<Transform2DProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Transform2DProto): Transform2DProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* u2.shared.proto.Vector2Proto position */ 1:
                    message.position = Vector2Proto.internalBinaryRead(reader, reader.uint32(), options, message.position);
                    break;
                case /* float rotation */ 2:
                    message.rotation = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Transform2DProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* u2.shared.proto.Vector2Proto position = 1; */
        if (message.position)
            Vector2Proto.internalBinaryWrite(message.position, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* float rotation = 2; */
        if (message.rotation !== 0)
            writer.tag(2, WireType.Bit32).float(message.rotation);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.Transform2DProto
 */
export const Transform2DProto = new Transform2DProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VelocityProto$Type extends MessageType<VelocityProto> {
    constructor() {
        super("u2.shared.proto.VelocityProto", [
            { no: 1, name: "linear", kind: "message", T: () => Vector2Proto },
            { no: 2, name: "angular", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<VelocityProto>): VelocityProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.angular = 0;
        if (value !== undefined)
            reflectionMergePartial<VelocityProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VelocityProto): VelocityProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* u2.shared.proto.Vector2Proto linear */ 1:
                    message.linear = Vector2Proto.internalBinaryRead(reader, reader.uint32(), options, message.linear);
                    break;
                case /* float angular */ 2:
                    message.angular = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VelocityProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* u2.shared.proto.Vector2Proto linear = 1; */
        if (message.linear)
            Vector2Proto.internalBinaryWrite(message.linear, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* float angular = 2; */
        if (message.angular !== 0)
            writer.tag(2, WireType.Bit32).float(message.angular);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.VelocityProto
 */
export const VelocityProto = new VelocityProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MassProto$Type extends MessageType<MassProto> {
    constructor() {
        super("u2.shared.proto.MassProto", [
            { no: 1, name: "mass_kg", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "inertia_kgm2", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<MassProto>): MassProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.massKg = 0;
        message.inertiaKgm2 = 0;
        if (value !== undefined)
            reflectionMergePartial<MassProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MassProto): MassProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float mass_kg */ 1:
                    message.massKg = reader.float();
                    break;
                case /* float inertia_kgm2 */ 2:
                    message.inertiaKgm2 = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MassProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float mass_kg = 1; */
        if (message.massKg !== 0)
            writer.tag(1, WireType.Bit32).float(message.massKg);
        /* float inertia_kgm2 = 2; */
        if (message.inertiaKgm2 !== 0)
            writer.tag(2, WireType.Bit32).float(message.inertiaKgm2);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.MassProto
 */
export const MassProto = new MassProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ControlStateProto$Type extends MessageType<ControlStateProto> {
    constructor() {
        super("u2.shared.proto.ControlStateProto", [
            { no: 1, name: "thrust", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "strafe_x", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 3, name: "strafe_y", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "yaw_input", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<ControlStateProto>): ControlStateProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.thrust = 0;
        message.strafeX = 0;
        message.strafeY = 0;
        message.yawInput = 0;
        if (value !== undefined)
            reflectionMergePartial<ControlStateProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ControlStateProto): ControlStateProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float thrust */ 1:
                    message.thrust = reader.float();
                    break;
                case /* float strafe_x */ 2:
                    message.strafeX = reader.float();
                    break;
                case /* float strafe_y */ 3:
                    message.strafeY = reader.float();
                    break;
                case /* float yaw_input */ 4:
                    message.yawInput = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ControlStateProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float thrust = 1; */
        if (message.thrust !== 0)
            writer.tag(1, WireType.Bit32).float(message.thrust);
        /* float strafe_x = 2; */
        if (message.strafeX !== 0)
            writer.tag(2, WireType.Bit32).float(message.strafeX);
        /* float strafe_y = 3; */
        if (message.strafeY !== 0)
            writer.tag(3, WireType.Bit32).float(message.strafeY);
        /* float yaw_input = 4; */
        if (message.yawInput !== 0)
            writer.tag(4, WireType.Bit32).float(message.yawInput);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.ControlStateProto
 */
export const ControlStateProto = new ControlStateProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FlightAssistProto$Type extends MessageType<FlightAssistProto> {
    constructor() {
        super("u2.shared.proto.FlightAssistProto", [
            { no: 1, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<FlightAssistProto>): FlightAssistProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.enabled = false;
        if (value !== undefined)
            reflectionMergePartial<FlightAssistProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FlightAssistProto): FlightAssistProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool enabled */ 1:
                    message.enabled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FlightAssistProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool enabled = 1; */
        if (message.enabled !== false)
            writer.tag(1, WireType.Varint).bool(message.enabled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.FlightAssistProto
 */
export const FlightAssistProto = new FlightAssistProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealthProto$Type extends MessageType<HealthProto> {
    constructor() {
        super("u2.shared.proto.HealthProto", [
            { no: 1, name: "current_hp", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "max_hp", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<HealthProto>): HealthProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.currentHp = 0;
        message.maxHp = 0;
        if (value !== undefined)
            reflectionMergePartial<HealthProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealthProto): HealthProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float current_hp */ 1:
                    message.currentHp = reader.float();
                    break;
                case /* float max_hp */ 2:
                    message.maxHp = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealthProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float current_hp = 1; */
        if (message.currentHp !== 0)
            writer.tag(1, WireType.Bit32).float(message.currentHp);
        /* float max_hp = 2; */
        if (message.maxHp !== 0)
            writer.tag(2, WireType.Bit32).float(message.maxHp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.HealthProto
 */
export const HealthProto = new HealthProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EntitySnapshotProto$Type extends MessageType<EntitySnapshotProto> {
    constructor() {
        super("u2.shared.proto.EntitySnapshotProto", [
            { no: 1, name: "entity_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "transform", kind: "message", T: () => Transform2DProto },
            { no: 3, name: "velocity", kind: "message", T: () => VelocityProto },
            { no: 4, name: "control_state", kind: "message", T: () => ControlStateProto },
            { no: 5, name: "flight_assist", kind: "message", T: () => FlightAssistProto },
            { no: 6, name: "health", kind: "message", T: () => HealthProto },
            { no: 7, name: "last_processed_sequence", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<EntitySnapshotProto>): EntitySnapshotProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.entityId = 0;
        message.lastProcessedSequence = 0;
        if (value !== undefined)
            reflectionMergePartial<EntitySnapshotProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntitySnapshotProto): EntitySnapshotProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 entity_id */ 1:
                    message.entityId = reader.uint32();
                    break;
                case /* u2.shared.proto.Transform2DProto transform */ 2:
                    message.transform = Transform2DProto.internalBinaryRead(reader, reader.uint32(), options, message.transform);
                    break;
                case /* u2.shared.proto.VelocityProto velocity */ 3:
                    message.velocity = VelocityProto.internalBinaryRead(reader, reader.uint32(), options, message.velocity);
                    break;
                case /* u2.shared.proto.ControlStateProto control_state */ 4:
                    message.controlState = ControlStateProto.internalBinaryRead(reader, reader.uint32(), options, message.controlState);
                    break;
                case /* u2.shared.proto.FlightAssistProto flight_assist */ 5:
                    message.flightAssist = FlightAssistProto.internalBinaryRead(reader, reader.uint32(), options, message.flightAssist);
                    break;
                case /* u2.shared.proto.HealthProto health */ 6:
                    message.health = HealthProto.internalBinaryRead(reader, reader.uint32(), options, message.health);
                    break;
                case /* uint32 last_processed_sequence */ 7:
                    message.lastProcessedSequence = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EntitySnapshotProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 entity_id = 1; */
        if (message.entityId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.entityId);
        /* u2.shared.proto.Transform2DProto transform = 2; */
        if (message.transform)
            Transform2DProto.internalBinaryWrite(message.transform, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.VelocityProto velocity = 3; */
        if (message.velocity)
            VelocityProto.internalBinaryWrite(message.velocity, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.ControlStateProto control_state = 4; */
        if (message.controlState)
            ControlStateProto.internalBinaryWrite(message.controlState, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.FlightAssistProto flight_assist = 5; */
        if (message.flightAssist)
            FlightAssistProto.internalBinaryWrite(message.flightAssist, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.HealthProto health = 6; */
        if (message.health)
            HealthProto.internalBinaryWrite(message.health, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* uint32 last_processed_sequence = 7; */
        if (message.lastProcessedSequence !== 0)
            writer.tag(7, WireType.Varint).uint32(message.lastProcessedSequence);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.EntitySnapshotProto
 */
export const EntitySnapshotProto = new EntitySnapshotProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WorldSnapshotProto$Type extends MessageType<WorldSnapshotProto> {
    constructor() {
        super("u2.shared.proto.WorldSnapshotProto", [
            { no: 1, name: "tick", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "timestamp_ms", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "entities", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EntitySnapshotProto }
        ]);
    }
    create(value?: PartialMessage<WorldSnapshotProto>): WorldSnapshotProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tick = 0;
        message.timestampMs = 0n;
        message.entities = [];
        if (value !== undefined)
            reflectionMergePartial<WorldSnapshotProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorldSnapshotProto): WorldSnapshotProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 tick */ 1:
                    message.tick = reader.uint32();
                    break;
                case /* uint64 timestamp_ms */ 2:
                    message.timestampMs = reader.uint64().toBigInt();
                    break;
                case /* repeated u2.shared.proto.EntitySnapshotProto entities */ 3:
                    message.entities.push(EntitySnapshotProto.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorldSnapshotProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 tick = 1; */
        if (message.tick !== 0)
            writer.tag(1, WireType.Varint).uint32(message.tick);
        /* uint64 timestamp_ms = 2; */
        if (message.timestampMs !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.timestampMs);
        /* repeated u2.shared.proto.EntitySnapshotProto entities = 3; */
        for (let i = 0; i < message.entities.length; i++)
            EntitySnapshotProto.internalBinaryWrite(message.entities[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.WorldSnapshotProto
 */
export const WorldSnapshotProto = new WorldSnapshotProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlayerInputProto$Type extends MessageType<PlayerInputProto> {
    constructor() {
        super("u2.shared.proto.PlayerInputProto", [
            { no: 1, name: "client_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "sequence_number", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "timestamp_ms", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "control_state", kind: "message", T: () => ControlStateProto },
            { no: 5, name: "flight_assist", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PlayerInputProto>): PlayerInputProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clientId = 0;
        message.sequenceNumber = 0;
        message.timestampMs = 0n;
        message.flightAssist = false;
        if (value !== undefined)
            reflectionMergePartial<PlayerInputProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayerInputProto): PlayerInputProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 client_id */ 1:
                    message.clientId = reader.uint32();
                    break;
                case /* uint32 sequence_number */ 2:
                    message.sequenceNumber = reader.uint32();
                    break;
                case /* uint64 timestamp_ms */ 3:
                    message.timestampMs = reader.uint64().toBigInt();
                    break;
                case /* u2.shared.proto.ControlStateProto control_state */ 4:
                    message.controlState = ControlStateProto.internalBinaryRead(reader, reader.uint32(), options, message.controlState);
                    break;
                case /* bool flight_assist */ 5:
                    message.flightAssist = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlayerInputProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 client_id = 1; */
        if (message.clientId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.clientId);
        /* uint32 sequence_number = 2; */
        if (message.sequenceNumber !== 0)
            writer.tag(2, WireType.Varint).uint32(message.sequenceNumber);
        /* uint64 timestamp_ms = 3; */
        if (message.timestampMs !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.timestampMs);
        /* u2.shared.proto.ControlStateProto control_state = 4; */
        if (message.controlState)
            ControlStateProto.internalBinaryWrite(message.controlState, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* bool flight_assist = 5; */
        if (message.flightAssist !== false)
            writer.tag(5, WireType.Varint).bool(message.flightAssist);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.PlayerInputProto
 */
export const PlayerInputProto = new PlayerInputProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectionAcceptedProto$Type extends MessageType<ConnectionAcceptedProto> {
    constructor() {
        super("u2.shared.proto.ConnectionAcceptedProto", [
            { no: 1, name: "client_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "entity_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "server_time_ms", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ConnectionAcceptedProto>): ConnectionAcceptedProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clientId = 0;
        message.entityId = 0;
        message.serverTimeMs = 0n;
        if (value !== undefined)
            reflectionMergePartial<ConnectionAcceptedProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectionAcceptedProto): ConnectionAcceptedProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 client_id */ 1:
                    message.clientId = reader.uint32();
                    break;
                case /* uint32 entity_id */ 2:
                    message.entityId = reader.uint32();
                    break;
                case /* uint64 server_time_ms */ 3:
                    message.serverTimeMs = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectionAcceptedProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 client_id = 1; */
        if (message.clientId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.clientId);
        /* uint32 entity_id = 2; */
        if (message.entityId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.entityId);
        /* uint64 server_time_ms = 3; */
        if (message.serverTimeMs !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.serverTimeMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.ConnectionAcceptedProto
 */
export const ConnectionAcceptedProto = new ConnectionAcceptedProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectionRequestProto$Type extends MessageType<ConnectionRequestProto> {
    constructor() {
        super("u2.shared.proto.ConnectionRequestProto", [
            { no: 1, name: "player_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConnectionRequestProto>): ConnectionRequestProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.playerName = "";
        message.version = "";
        if (value !== undefined)
            reflectionMergePartial<ConnectionRequestProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectionRequestProto): ConnectionRequestProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string player_name */ 1:
                    message.playerName = reader.string();
                    break;
                case /* string version */ 2:
                    message.version = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectionRequestProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string player_name = 1; */
        if (message.playerName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.playerName);
        /* string version = 2; */
        if (message.version !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.version);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.ConnectionRequestProto
 */
export const ConnectionRequestProto = new ConnectionRequestProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DisconnectProto$Type extends MessageType<DisconnectProto> {
    constructor() {
        super("u2.shared.proto.DisconnectProto", [
            { no: 1, name: "client_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DisconnectProto>): DisconnectProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clientId = 0;
        message.reason = "";
        if (value !== undefined)
            reflectionMergePartial<DisconnectProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DisconnectProto): DisconnectProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 client_id */ 1:
                    message.clientId = reader.uint32();
                    break;
                case /* string reason */ 2:
                    message.reason = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DisconnectProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 client_id = 1; */
        if (message.clientId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.clientId);
        /* string reason = 2; */
        if (message.reason !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.reason);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.DisconnectProto
 */
export const DisconnectProto = new DisconnectProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientMessageProto$Type extends MessageType<ClientMessageProto> {
    constructor() {
        super("u2.shared.proto.ClientMessageProto", [
            { no: 1, name: "connection_request", kind: "message", oneof: "message", T: () => ConnectionRequestProto },
            { no: 2, name: "player_input", kind: "message", oneof: "message", T: () => PlayerInputProto }
        ]);
    }
    create(value?: PartialMessage<ClientMessageProto>): ClientMessageProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ClientMessageProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientMessageProto): ClientMessageProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* u2.shared.proto.ConnectionRequestProto connection_request */ 1:
                    message.message = {
                        oneofKind: "connectionRequest",
                        connectionRequest: ConnectionRequestProto.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).connectionRequest)
                    };
                    break;
                case /* u2.shared.proto.PlayerInputProto player_input */ 2:
                    message.message = {
                        oneofKind: "playerInput",
                        playerInput: PlayerInputProto.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).playerInput)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClientMessageProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* u2.shared.proto.ConnectionRequestProto connection_request = 1; */
        if (message.message.oneofKind === "connectionRequest")
            ConnectionRequestProto.internalBinaryWrite(message.message.connectionRequest, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.PlayerInputProto player_input = 2; */
        if (message.message.oneofKind === "playerInput")
            PlayerInputProto.internalBinaryWrite(message.message.playerInput, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.ClientMessageProto
 */
export const ClientMessageProto = new ClientMessageProto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerMessageProto$Type extends MessageType<ServerMessageProto> {
    constructor() {
        super("u2.shared.proto.ServerMessageProto", [
            { no: 1, name: "connection_accepted", kind: "message", oneof: "message", T: () => ConnectionAcceptedProto },
            { no: 2, name: "world_snapshot", kind: "message", oneof: "message", T: () => WorldSnapshotProto },
            { no: 3, name: "disconnect", kind: "message", oneof: "message", T: () => DisconnectProto }
        ]);
    }
    create(value?: PartialMessage<ServerMessageProto>): ServerMessageProto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ServerMessageProto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerMessageProto): ServerMessageProto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* u2.shared.proto.ConnectionAcceptedProto connection_accepted */ 1:
                    message.message = {
                        oneofKind: "connectionAccepted",
                        connectionAccepted: ConnectionAcceptedProto.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).connectionAccepted)
                    };
                    break;
                case /* u2.shared.proto.WorldSnapshotProto world_snapshot */ 2:
                    message.message = {
                        oneofKind: "worldSnapshot",
                        worldSnapshot: WorldSnapshotProto.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).worldSnapshot)
                    };
                    break;
                case /* u2.shared.proto.DisconnectProto disconnect */ 3:
                    message.message = {
                        oneofKind: "disconnect",
                        disconnect: DisconnectProto.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).disconnect)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerMessageProto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* u2.shared.proto.ConnectionAcceptedProto connection_accepted = 1; */
        if (message.message.oneofKind === "connectionAccepted")
            ConnectionAcceptedProto.internalBinaryWrite(message.message.connectionAccepted, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.WorldSnapshotProto world_snapshot = 2; */
        if (message.message.oneofKind === "worldSnapshot")
            WorldSnapshotProto.internalBinaryWrite(message.message.worldSnapshot, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* u2.shared.proto.DisconnectProto disconnect = 3; */
        if (message.message.oneofKind === "disconnect")
            DisconnectProto.internalBinaryWrite(message.message.disconnect, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message u2.shared.proto.ServerMessageProto
 */
export const ServerMessageProto = new ServerMessageProto$Type();
